name: Azure Deploy Workflow Test

on:
  workflow_run:
    workflows: ["GCP Deploy Workflow"]
    types: [completed]
  
env:
  DOCKER_REPOSITORY: foodsvc
  PORT_TO_BE_EXPOSED: 8080

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.deployment.environment }}
    steps:
      - uses: hmarr/debug-action@v2
      - name: Load environment variables
        run: |
          echo "DEPLOYMENT_REF=https://api.github.com/repos/${{ github.event.deployment.ref  }}" 
          echo "DEPLOYMENT_ENV=https://api.github.com/repos/${{ github.event.deployment.environment  }}"
          echo "DEPLOYMENT_CONCLUSION=https://api.github.com/repos/${{ github.event.workflow_run.conclusion }}" 
          echo "DEPLOYMENT_RUN=https://api.github.com/repos/${{ github.event.workflow_run  }}" 
          echo "DEPLOYMENT_EN=https://api.github.com/repos/${{ github.event.workflow_run.environment  }}" 
          echo "DEPLOYMENT_DEP=https://api.github.com/repos/${{ github.event.workflow_run.deployment.environment  }}" 


          echo "DEPLOYMENT_API=https://api.github.com/repos/${{ github.repository }}/deployments" >> $GITHUB_ENV
          echo "DOCKER_REPOSITORY=task-dev" >> $GITHUB_ENV
          echo "PROJECT_NAME=rgv-dev" >> $GITHUB_ENV

          echo "DOCKER_REPOSITORY=task-qa" >> $GITHUB_ENV
          echo "PROJECT_NAME=rgv-qa" >> $GITHUB_ENV

          else
          exit 1

          fi

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
