name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Trigger Dev Deployment (if this is commit to master)
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
         echo "GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}" 
         DEPLOYMENT_API="https://api.github.com/repos/${{ github.repository }}/deployments"
         curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d '{"ref":"master","environment":"Dev","required_contexts":[]}' "$DEPLOYMENT_API"
